### ISSUE TITLE
[BUG] Failed to run

### ISSUE THREAD

**Issue by SnowyThinker** [SAP/e-mobility-charging-stations-simulator#568]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

Failed to run command
~~~sh
pnpm start
~~~

### e-mobility-charging-stations-simulator version

main branch

### Node.js Version

v18.12.1

### System

  System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 3.78 GB / 15.91 GB

### Expected result

start the simulator

### Actual result

start the simulator

### Attachments

λ pnpm start

> e-mobility-charging-stations-simulator@1.2.13 start E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13
> pnpm build && cross-env NODE_ENV=production node -r source-map-support/register dist/start.mjs

> e-mobility-charging-stations-simulator@1.2.13 build E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13
> pnpm rollup

> e-mobility-charging-stations-simulator@1.2.13 rollup E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13
> pnpm build-requirements && rollup --config

> e-mobility-charging-stations-simulator@1.2.13 build-requirements E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13
> node --no-warnings build-requirements.mjs

src/start.ts, src/charging-station/ChargingStationWorker.ts → dist...
(!) Circular dependencies
src/charging-station/internal.ts -> src/charging-station/IdTagsCache.ts -> src/charging-station/internal.ts
src/types/internal.ts -> src/types/ocpp/ChargePointErrorCode.ts -> src/types/internal.ts
src/types/internal.ts -> src/types/ocpp/ChargingProfile.ts -> src/types/internal.ts
...and 45 more
(!) Unused external imports
ManyToOne,PrimaryKey,Property,Collection,OneToMany,Configuration,Connection imported from external module "@mikro-orm/core" but never used in "src/performance/storage/MikroOrmStorage.ts", "src/types/orm/entities/PerformanceRecord.ts" and "src/types/orm/entities/PerformanceData.ts".
created dist in 9.1s
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, open 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:344:14)
    at Function.getLogRotate (file:///E:/Workbench/node/src/utils/Configuration.ts:239:43)
    at file:///E:/Workbench/node/src/utils/Logger.ts:11:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, watch 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at Function.getConfigurationFileWatcher (file:///E:/Workbench/node/src/utils/Configuration.ts:364:17)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:356:64)
    at Function.getLogRotate (file:///E:/Workbench/node/src/utils/Configuration.ts:239:43)
    at file:///E:/Workbench/node/src/utils/Logger.ts:11:19
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json',
  filename: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, open 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:344:14)
    at Function.getLogMaxFiles (file:///E:/Workbench/node/src/utils/Configuration.ts:246:38)
    at file:///E:/Workbench/node/src/utils/Logger.ts:12:37
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, watch 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at Function.getConfigurationFileWatcher (file:///E:/Workbench/node/src/utils/Configuration.ts:364:17)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:356:64)
    at Function.getLogMaxFiles (file:///E:/Workbench/node/src/utils/Configuration.ts:246:38)
    at file:///E:/Workbench/node/src/utils/Logger.ts:12:37
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json',
  filename: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, open 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:344:14)
    at Function.getLogMaxSize (file:///E:/Workbench/node/src/utils/Configuration.ts:253:38)
    at file:///E:/Workbench/node/src/utils/Logger.ts:13:36
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, watch 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at Function.getConfigurationFileWatcher (file:///E:/Workbench/node/src/utils/Configuration.ts:364:17)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:356:64)
    at Function.getLogMaxSize (file:///E:/Workbench/node/src/utils/Configuration.ts:253:38)
    at file:///E:/Workbench/node/src/utils/Logger.ts:13:36
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json',
  filename: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, open 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:344:14)
    at Function.warnDeprecatedConfigurationKey (file:///E:/Workbench/node/src/utils/Configuration.ts:330:49)
    at Function.getLogErrorFile (file:///E:/Workbench/node/src/utils/Configuration.ts:271:19)
    at file:///E:/Workbench/node/src/utils/Logger.ts:17:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
5/23/2023, 4:56:40 PM Simulator configuration | configuration file E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json not found:  Error: ENOENT: no such file or directory, watch 'E:\Workbench\node\e-mobility-charging-stations-simulator-1.2.13\dist\assets\config.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2315:34)
    at Function.getConfigurationFileWatcher (file:///E:/Workbench/node/src/utils/Configuration.ts:364:17)
    at Function.getConfig (file:///E:/Workbench/node/src/utils/Configuration.ts:356:64)
    at Function.warnDeprecatedConfigurationKey (file:///E:/Workbench/node/src/utils/Configuration.ts:330:49)
    at Function.getLogErrorFile (file:///E:/Workbench/node/src/utils/Configuration.ts:271:19)
    at file:///E:/Workbench/node/src/utils/Logger.ts:17:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24) {
  errno: -4058,
  syscall: 'watch',
  code: 'ENOENT',
  path: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json',
  filename: 'E:\\Workbench\\node\\e-mobility-charging-stations-simulator-1.2.13\\dist\\assets\\config.json'
}
TypeError: Cannot read properties of null (reading 'errorFile')
    at Function.warnDeprecatedConfigurationKey (file:///E:/Workbench/node/src/utils/Configuration.ts:330:49)
    at Function.getLogErrorFile (file:///E:/Workbench/node/src/utils/Configuration.ts:271:19)
    at file:///E:/Workbench/node/src/utils/Logger.ts:17:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at loadESM (node:internal/process/esm_loader:91:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by jerome-benoit** [comment]
Not a bug.
